/**
 * new_jokes.js — Additional Joke data for the Math Jokes Worksheet Generator
 *
 * This file contains new jokes in the same format as the original jokes.js
 * Each joke has:
 *   id       {number} — A unique numeric identifier for the joke.
 *   filename {string} — A "slug" (URL-friendly name) used to name the PDF file.
 *   joke_q   {string} — The joke QUESTION (shown on the worksheet).
 *   joke_a   {string} — The joke ANSWER (8-15 characters, used for the letter grid).
 */
const newJokes = [
    { id: 2000001, filename: 'sad_strawberry',        joke_q: 'What do you call a sad strawberry?',                                                  joke_a: 'A Blueberry' },
    { id: 2000002, filename: 'lion_comedian',         joke_q: 'What happened when the lion ate the comedian?',                                       joke_a: 'He Felt Funny' },
    { id: 2000003, filename: 'dandy_lion',            joke_q: 'When is a well-dressed lion like a weed?',                                            joke_a: 'A Dandelion' },
    { id: 2000004, filename: 'fish_schools',          joke_q: 'Why are fish so smart?',                                                              joke_a: 'They Live in Schools' },
    { id: 2000005, filename: 'snail_house',           joke_q: 'What is the strongest animal?',                                                       joke_a: 'A Snail' },
    { id: 2000006, filename: 'teddy_bears_hungry',    joke_q: 'Why are teddy bears never hungry?',                                                   joke_a: 'Always Stuffed' },
    { id: 2000007, filename: 'fish_salt_water',       joke_q: 'Why do fish live in salt water?',                                                     joke_a: 'Pepper Sneezes' },
    { id: 2000008, filename: 'polar_bear_vote',       joke_q: 'Where do polar bears vote?',                                                          joke_a: 'The North Poll' },
    { id: 2000009, filename: 'skunk_court',           joke_q: 'What did the judge say when the skunk walked into court?',                            joke_a: 'Odor in Court' },
    { id: 2000010, filename: 'chicken_egg_barn',      joke_q: 'What do you get when a chicken lays an egg on top of a barn?',                        joke_a: 'An Eggroll' },
    { id: 2000011, filename: 'snake_pie',             joke_q: 'What do you get when you cross a snake and a pie?',                                   joke_a: 'A Pie-thon' },
    { id: 2000012, filename: 'buffalo_son',           joke_q: 'What did the buffalo say to his son when he went away?',                              joke_a: 'Bison' },
    { id: 2000013, filename: 'starfish_night',        joke_q: 'What fish only swims at night?',                                                      joke_a: 'A Starfish' },
    { id: 2000014, filename: 'bees_school',           joke_q: 'How do bees get to school?',                                                          joke_a: 'School Buzz' },
    { id: 2000015, filename: 'bear_no_ears',          joke_q: 'What do you call a bear with no ears?',                                               joke_a: 'B' },
    { id: 2000016, filename: 'frogs_croak',           joke_q: 'What animal has more lives than a cat?',                                              joke_a: 'Frogs' },
    { id: 2000017, filename: 'panda_movies',          joke_q: 'Why do pandas like old movies?',                                                      joke_a: 'Black & White' },
    { id: 2000018, filename: 'mice_boats',            joke_q: 'Where do mice park their boats?',                                                     joke_a: 'Hickory Dock' },
    { id: 2000019, filename: 'alligator_spyglass',    joke_q: 'What do you call an alligator with a spyglass?',                                      joke_a: 'Investigator' },
    { id: 2000020, filename: 'sheep_vacation',        joke_q: 'Where did the sheep go on vacation?',                                                 joke_a: 'The Baaaahamas' },
    { id: 2000021, filename: 'depressed_zebra',       joke_q: "What's black and white and blue?",                                                    joke_a: 'Depressed Zebra' },
    { id: 2000022, filename: 'chicken_fry_days',      joke_q: 'What day do chickens fear the most?',                                                 joke_a: 'Fry-days' },
    { id: 2000023, filename: 'elephant_charging',     joke_q: 'How do you stop an elephant from charging?',                                          joke_a: 'Take the Card' },
    { id: 2000024, filename: 'robber_ducky',          joke_q: 'Who stole the soap out of the bathtub?',                                              joke_a: 'Robber Ducky' },
    { id: 2000025, filename: 'firequackers',          joke_q: 'What do you get if you cross fireworks with a duck?',                                 joke_a: 'Firequackers' },
    { id: 2000026, filename: 'lion_greet',            joke_q: 'How does a lion greet the other animals in the field?',                               joke_a: 'Pleased to Eat' },
    { id: 2000027, filename: 'snake_math',            joke_q: 'What kind of snake is good at math?',                                                 joke_a: 'An Adder' },
    { id: 2000028, filename: 'ocean_wave',            joke_q: 'What did one ocean say to the other ocean?',                                          joke_a: 'Nothing' },
    { id: 2000029, filename: 'bicycle_stand',         joke_q: "Why couldn't the bicycle stand up by itself?",                                        joke_a: 'Two-tired' },
    { id: 2000030, filename: 'pirates_letter',        joke_q: "What's a pirate's favorite letter?",                                                  joke_a: 'Arrrt' },
    { id: 2000031, filename: 'bumblebee_candy',       joke_q: 'What candy do bumblebees love the most?',                                             joke_a: 'Bumble Gum' },
    { id: 2000032, filename: 'peter_pan_fly',         joke_q: 'Why does Peter Pan fly around so much?',                                              joke_a: 'He Neverlands' },
    { id: 2000033, filename: 'car_gas',               joke_q: 'What starts with gas and has three letters?',                                         joke_a: 'A Car' },
    { id: 2000034, filename: 'corners_meet',          joke_q: 'What did one wall say to the other wall?',                                            joke_a: 'Meet at Corner' },
    { id: 2000035, filename: 'stadium_fans',          joke_q: "Why wasn't the stadium hot after the game?",                                          joke_a: 'So Many Fans' },
    { id: 2000036, filename: 'cinderella_football',   joke_q: 'Why is Cinderella so bad at playing football?',                                       joke_a: 'Runs from Ball' },
    { id: 2000037, filename: 'baseball_bat',          joke_q: "What's one animal you'll always find at a baseball game?",                            joke_a: 'A Bat' },
    { id: 2000038, filename: 'horses_live',           joke_q: 'Where do most horses live?',                                                          joke_a: 'Neigh-borhoods' },
    { id: 2000039, filename: 'neptune_sing',          joke_q: 'Which planet loves to sing?',                                                         joke_a: 'Nep-tune' },
    { id: 2000040, filename: 'basketball_wet',        joke_q: 'Why are basketball courts always wet?',                                               joke_a: 'Players Dribble' },
    { id: 2000041, filename: 'sweet_keys',            joke_q: 'What kind of keys are sweet?',                                                        joke_a: 'Cookies' },
    { id: 2000042, filename: 'peanut_rocket',         joke_q: 'Why did the peanut get into a rocket?',                                               joke_a: 'Astro-nut' },
    { id: 2000043, filename: 'twins_fruit',           joke_q: 'What fruit do twins love?',                                                           joke_a: 'Pears' },
    { id: 2000044, filename: 'bees_hair',             joke_q: 'How do bees brush their hair?',                                                       joke_a: 'Honeycombs' },
    { id: 2000045, filename: 'snails_eat',            joke_q: 'Who eats snails?',                                                                    joke_a: 'Fast Food' },
    { id: 2000046, filename: 'banana_doctor',         joke_q: 'Why did the banana visit the doctor?',                                                joke_a: 'Not Peeling' },
    { id: 2000047, filename: 'smartest_insect',       joke_q: "What's the smartest insect?",                                                         joke_a: 'Spelling Bee' },
    { id: 2000048, filename: 'palm_tree_hand',        joke_q: 'What kind of tree you can hold in your hand?',                                        joke_a: 'A Palm Tree' },
    { id: 2000049, filename: 'music_keys',            joke_q: 'Where did the music teacher leave her keys?',                                         joke_a: 'In the Piano' },
    { id: 2000050, filename: 'barber_drive',          joke_q: 'How does a barber drive to work?',                                                    joke_a: 'He Takes Cuts' },
    { id: 2000051, filename: 'ducks_cash',            joke_q: 'Why do ducks always pay with cash?',                                                  joke_a: 'They Have Bills' },
    { id: 2000052, filename: 'cow_grass',             joke_q: 'What do you call a cow that eats your grass?',                                        joke_a: 'A Lawn Moo-er' },
    { id: 2000053, filename: 'girl_frog',             joke_q: 'What do you call a girl with a frog on her head?',                                    joke_a: 'Lilly' },
    { id: 2000054, filename: 'candle_young',          joke_q: "I'm tall when I'm young and short when I'm old. What am I?",                          joke_a: 'A Candle' },
    { id: 2000055, filename: 'egg_broken',            joke_q: 'What has to be broken before you can use it?',                                        joke_a: 'An Egg' },
    { id: 2000056, filename: 'catch_cold',            joke_q: 'What can you catch but not throw?',                                                   joke_a: 'A Cold' },
    { id: 2000057, filename: 'coin_head',             joke_q: 'What has a head, a tail, but no body?',                                               joke_a: 'A Coin' },
    { id: 2000058, filename: 'teapot_t',              joke_q: 'What begins with T, ends with T, and has T in it?',                                   joke_a: 'A Teapot' },
    { id: 2000059, filename: 'bed_legs',              joke_q: 'What has one head, one foot and four legs?',                                          joke_a: 'A Bed' },
    { id: 2000060, filename: 'roof_joke',             joke_q: 'Did you hear the joke about the roof?',                                               joke_a: 'Over Your Head' },
    { id: 2000061, filename: 'cold_two_letters',      joke_q: 'How can you spell cold with two letters?',                                            joke_a: 'IC' },
    { id: 2000062, filename: 'david_sons',            joke_q: "David's father had three sons: Snap, Crackle, and what?",                             joke_a: 'David' },
    { id: 2000063, filename: 'gravity_center',        joke_q: 'What is the center of gravity?',                                                      joke_a: 'The Letter V' },
    { id: 2000064, filename: 'bookkeeper_letters',    joke_q: 'What English word has three consecutive double letters?',                             joke_a: 'Bookkeeper' },
    { id: 2000065, filename: 'penny_brown',           joke_q: 'What has a head, a tail, is brown, and has no legs?',                                 joke_a: 'A Penny' },
    { id: 2000066, filename: 'cloud_fly',             joke_q: 'I have no wings, but I can fly. I have no eyes, but I can cry. What am I?',           joke_a: 'A Cloud' },
    { id: 2000067, filename: 'breath_light',          joke_q: "I'm light as a feather, but the world's strongest man couldn't hold me long. What am I?", joke_a: 'Breath' },
    { id: 2000068, filename: 'your_name',             joke_q: 'It belongs to you, but your friends use it more. What is it?',                        joke_a: 'Your Name' },
    { id: 2000069, filename: 'kate_children',         joke_q: "Kate's mother has three children: Snap, Crackle and ___?",                            joke_a: 'Kate' },
    { id: 2000070, filename: 'promise_kept',          joke_q: 'What can you break without touching it?',                                             joke_a: 'A Promise' },
    { id: 2000071, filename: 'wrong_dictionary',      joke_q: "There's only one word in the dictionary that's spelled wrong. What is it?",           joke_a: 'Wrong' },
    { id: 2000072, filename: 'race_second',           joke_q: "You're running a race and pass the person in 2nd place. What place are you in?",      joke_a: 'Second Place' },
    { id: 2000073, filename: 'lunch_dinner',          joke_q: 'What 2 things can you never eat for breakfast?',                                      joke_a: 'Lunch & Dinner' },
    { id: 2000074, filename: 'brother_grant',         joke_q: 'When Grant was 8, his brother was half his age. Now Grant is 14. How old is his brother?', joke_a: 'Ten Years Old' },
    { id: 2000075, filename: 'staircase_move',        joke_q: 'I go up and down, but never move. What am I?',                                        joke_a: 'A Staircase' },
    { id: 2000076, filename: 'stamp_travel',          joke_q: 'What can travel around the world while staying in a corner?',                         joke_a: 'A Stamp' },
    { id: 2000077, filename: 'rain_falls',            joke_q: 'What falls but never gets hurt?',                                                     joke_a: 'Rain' },
    { id: 2000078, filename: 'towel_wet',             joke_q: 'What gets wetter the more it dries?',                                                 joke_a: 'A Towel' },
    { id: 2000079, filename: 'piano_keys',            joke_q: 'What has many keys but cannot open any doors?',                                       joke_a: 'A Piano' },
    { id: 2000080, filename: 'mushroom_fun',          joke_q: 'Why does everyone like to hang out with a mushroom?',                                 joke_a: 'Real Funghi' },
];
