jokes = [
    {"id":1000001, "filename":"dogs_tell_time", "joke_q":"What kind of dogs can tell time?", "joke_a":"Watch Dogs"},
    {"id":1000002, "filename":"platypus_hole", "joke_q":"What do you call a platypus that falls in a hole?", "joke_a":"A Splatypus"},
    {"id":1000003, "filename":"monkey_breakfast", "joke_q":"What does a monkey drink with its breakfast?", "joke_a":"Ape Juice"},
    {"id":1000004, "filename":"pigs_dirty_laundry", "joke_q":"Where do pigs put their dirty laundry?", "joke_a":"In The Hamper"},
    {"id":1000005, "filename":"dog_mosquito", "joke_q":"What do you get if you cross a dog and a mosquito?", "joke_a":"Bloodhound"},
    {"id":1000006, "filename":"squirrel_breakfast", "joke_q":"What does a squirrel like to eat for breakfast?", "joke_a":"Dough-Nuts"},
    {"id":1000007, "filename":"firefly_lunch", "joke_q":"What did the firefly have for lunch?", "joke_a":"A Light Meal"},
    {"id":1000008, "filename":"birds_stick_together", "joke_q":"What kind of birds like to stick together?", "joke_a":"Vel-Crows"},
    {"id":1000009, "filename":"dog_snowman", "joke_q":"What do you get when you cross a dog and a snowman?", "joke_a":"Frostbite"},
    {"id":1000010, "filename":"cat_night", "joke_q":"What does a cat wear at night?", "joke_a":"Paw-jamas"},
    {"id":1000011, "filename":"cow_vegetable", "joke_q":"What is a cow's favorite vegetable?", "joke_a":"Cow-iflower"},
    {"id":1000012, "filename":"cow_toad", "joke_q":"What do you get when you cross a cow and a toad?", "joke_a":"A Bullfrog"},
    {"id":1000013, "filename":"woodpecker_breakfast", "joke_q":"What do woodpeckers eat for breakfast?", "joke_a":"Oakmeal"},
    {"id":1000014, "filename":"pig_karate", "joke_q":"What do you get when a pig does karate?", "joke_a":"Pork chops"},
    {"id":1000015, "filename":"frog_snack", "joke_q":"What is a frogs favorite snack?", "joke_a":"French flies"},
    {"id":1000016, "filename":"bronto_lemon", "joke_q":"What do you get when you cross a brontosaurus and a lemon?", "joke_a":"A Dinosour"},
    {"id":1000017, "filename":"monkey_behave", "joke_q":"What do you call a monkey who won't behave?", "joke_a":"A Bad-Boon"},
    {"id":1000018, "filename":"elephant_vader", "joke_q":"What do you get when you cross an elephant with Darth Vader?", "joke_a":"An Ele-vader"},
    {"id":1000019, "filename":"bread_bed", "joke_q":"What did the slice of bread wear to bed?", "joke_a":"Its Jam-mies"},
    {"id":1000020, "filename":"bear_rain", "joke_q":"What do you call a bear standing in the rain?", "joke_a":"A Drizzly Bear"},
    {"id":1000021, "filename":"boomerang", "joke_q":"What do you call a boomerang that wont come back?", "joke_a":"A Stick"},
    {"id":1000022, "filename":"cloud_coat", "joke_q":"What do clouds wear under their shorts?", "joke_a":"Thunderwear"},
    {"id":1000023, "filename":"friendly_ocean", "joke_q":"How do we know that the ocean is friendly?", "joke_a":"It waves"},
    {"id":1000024, "filename":"giant_talk", "joke_q":"How do you talk to a giant?", "joke_a":"Use big word"},
    {"id":1000025, "filename":"tree_hand", "joke_q":"What kind of tree fits in your hand?", "joke_a":"A palm tree"},
    {"id":1000026, "filename":"birthday_end", "joke_q":"What does every birthday end with?", "joke_a":"The letter Y"},
    {"id":1000027, "filename":"cow_no_milk", "joke_q":"What do you call a cow that wont give milk?", "joke_a":"A milk dud"},
    {"id":1000028, "filename":"sleeping_bull", "joke_q":"What do you call a sleeping bull?", "joke_a":"A bull-dozer"},
    {"id":1000029, "filename":"ghost_nose", "joke_q":"What is a ghosts nose full of?", "joke_a":"Boo-gers"},
    {"id":1000030, "filename":"skeleton_instrument", "joke_q":"What instrument does a skeleton play?", "joke_a":"A Trom-bone"},
    {"id":1000031, "filename":"turkey_feathers", "joke_q":"Which side of the turkey has the most feathers?", "joke_a":"The Outside"},
    {"id":1000032, "filename":"merry_sheep", "joke_q":"How does a sheep say Merry Christmas?", "joke_a":"Fleece Navidad"},
    {"id":1000033, "filename":"space_party", "joke_q":"How do you organize a space party?", "joke_a":"You planet"},
    {"id":1000034, "filename":"janitor_closet", "joke_q":"What did the janitor say when he jumped out of the closet?", "joke_a":"Supplies!"},
    {"id":1000035, "filename":"bear_teeth", "joke_q":"What do you call a bear with no teeth?", "joke_a":"Gummy bear"},
    {"id":1000036, "filename":"watch_belt", "joke_q":"What do you call a belt made out of watches?", "joke_a":"Waist of time"},
    {"id":1000037, "filename":"snowman_july", "joke_q":"What do you call a snowman in July?", "joke_a":"A puddle"},
    {"id":1000038, "filename":"your_cheese", "joke_q":"What do you call cheese that isn't yours?", "joke_a":"Nacho cheese"},
    {"id":1000039, "filename":"fake_spaghetti", "joke_q":"What do you call fake spaghetti?", "joke_a":"An impasta"},
    {"id":1000040, "filename":"orange_parrot", "joke_q":"What's orange and sounds like a parrot?", "joke_a":"A carrot"},
    {"id":1000041, "filename":"cheerleader_drink", "joke_q":"What's a cheerleader's favorite drink?", "joke_a":"Root Beer"},
    {"id":1000042, "filename":"cat_pile", "joke_q":"What do you call a pile of cats? ", "joke_a":"A meowtain"},
    {"id":1000043, "filename":"cow_legs", "joke_q":"What do you call a cow with no legs?", "joke_a":"Ground Beef"},
    {"id":1000044, "filename":"alligator_vest", "joke_q":"What do you call an alligator in a vest?", "joke_a":"Investigator"},
    {"id":1000045, "filename":"deer_eyes", "joke_q":"What do you call a deer with no eyes?", "joke_a":"No idea"},
    {"id":1000046, "filename":"bee_mind", "joke_q":"What do you call a bee that can't make up its mind?", "joke_a":"A Maybee"},
    {"id":1000047, "filename":"magic_owl", "joke_q":"What do you call a magic owl?", "joke_a":"Whooo-dini"},
    {"id":1000048, "filename":"cat_water", "joke_q":"What do you call a cat that loves water?", "joke_a":"A Purrmaid"},
    {"id":1000049, "filename":"snake_jokes", "joke_q":"What do you call a snake that tells jokes?", "joke_a":"Hiss-terical"},
    {"id":1000050, "filename":"cat_beans", "joke_q":"What do you call a cat that likes to eat beans?", "joke_a":"A Purr-ito"},
    {"id":1000051, "filename":"bird_math", "joke_q":"What is a bird's favorite type of math?", "joke_a":"Owl-gebra"},
    {"id":1000052, "filename":"astronaut_computer", "joke_q":"What is an astronaut’s favorite part of a computer?", "joke_a":"Space Bar"},
    {"id":1000053, "filename":"tricycle_bicycle", "joke_q":"What is the difference between a poorly dressed man on a tricycle, and a well-dressed man on a bicycle?", "joke_a":"Attire"},
    {"id":1000054, "filename":"bagel_fly", "joke_q":"What do you call a bagel that can fly?", "joke_a":"Plain Bagel"},
    {"id":1000055, "filename":"triangle_circl", "joke_q":"What does a triangle call a circle?", "joke_a":"Pointless"},
    {"id":1000056, "filename":"aardvark_feet", "joke_q":"What do you call an aardvark that is three feet long?", "joke_a":"A Yardvark"},
    {"id":1000057, "filename":"pony_throat", "joke_q":"What do you call a pony with a sore throat?", "joke_a":"A Little Horse"},
    {"id":1000058, "filename":"red_bllue", "joke_q":"What is red and smells like blue paint?", "joke_a":"Red Paint"},
    {"id":1000059, "filename":"foot_slippery", "joke_q":"What’s a foot long and slippery?", "joke_a":"A Slipper"},
    {"id":1000060, "filename":"rubber_toe", "joke_q":"What do you call a man with a rubber toe?", "joke_a":"Roberto"},
    {"id":1000061, "filename":"meditating_wolf", "joke_q":"What do you call a meditating wolf?", "joke_a":"Aware Wolf"},
    {"id":1000062, "filename":"spelled_incorrectly", "joke_q":"What word is spelled incorrectly in every dictionary?", "joke_a":"Incorrectly"},
    {"id":1000063, "filename":"end_rainbow", "joke_q":"What is at the end of every rainbow?", "joke_a":"The letter W"},
    {"id":1000064, "filename":"one_letter", "joke_q":"What start with an E, ends with an E, but only contains one letter?", "joke_a":"An Envelope"},
    {"id":1000065, "filename":"call_dentist", "joke_q":"When is the best time to call your dentist?", "joke_a":"Tooth-hurty"},
    {"id":1000066, "filename":"astronaut_baby", "joke_q":"How do you get an astronaut’s baby to stop crying?", "joke_a":"You rocket"},
    {"id":1000067, "filename":"girl_tennis", "joke_q":"What do you call a girl in the middle of a tennis court?", "joke_a":"Annette"},
    {"id":1000068, "filename":"sandals_frog", "joke_q":"What kind of sandals do frogs wear?", "joke_a":"Open-Toad"},
    {"id":1000069, "filename":"potato_glasses", "joke_q":"What do you call a potato wearing glasses?", "joke_a":"A Spec-Tater"},
    {"id":1000070, "filename":"moose_name", "joke_q":"What do you call a moose with no name?", "joke_a":"Anonymoose"},
    {"id":1000071, "filename":"music_planet", "joke_q":"What type of music do the planets enjoy?", "joke_a":"Neptunes"},
    {"id":1000072, "filename":"rancher_cattle", "joke_q":"What does a rancher use to count his cattle?", "joke_a":"A Cow-culator"},
    {"id":1000073, "filename":"pampered_cow", "joke_q":"What do you get from a pampered cow?", "joke_a":"Spoiled Milk"},
    {"id":1000074, "filename":"computer_snack", "joke_q":"What do computers eat for a snack?", "joke_a":"Microchips"},
    {"id":1000075, "filename":"face_hands", "joke_q":"What has a face and two hands, but no arms or legs?", "joke_a":"A Clock"},
    {"id":1000076, "filename":"shorter_add", "joke_q":"What word becomes shorter after you add two letters to it?", "joke_a":"Short"},
    {"id":1000077, "filename":"twice_moment", "joke_q":"What occurs once in a minute, twice in a moment, and never in one thousand years?", "joke_a":"The letter M"},
    {"id":1000078, "filename":"fragile_name", "joke_q":"I am so fragile that if you say my name, you will break me. What am I?", "joke_a":"Silence"},
    {"id":1000079, "filename":"most_letters", "joke_q":"What two words, when combined, hold the most letters?", "joke_a":"Post Office"},
    {"id":1000080, "filename":"wheels_flies", "joke_q":"What has 4 wheels and flies?", "joke_a":"A Garbage Truck"},
    {"id":1000081, "filename":"three_feet", "joke_q":"What has three feet but can’t walk?", "joke_a":"A Yardstick"},
    {"id":1000082, "filename":"elephant_nothing", "joke_q":"What is as big as an elephant but weighs absolutely nothing?", "joke_a":"Its Shadow"},
]
